framework:
    secret: '%env(APP_SECRET)%'
    default_locale: fr
    csrf_protection: ~
    session:
        handler_id: ~
    php_errors:
        log: true
    translator:
        fallbacks: [ "fr" ]
    assets:
        json_manifest_path: '%kernel.project_dir%/public/build/manifest.json'
