security:
    encoders:
        App\Entity\Admin:
            algorithm: bcrypt
            cost: 6
    providers:
        db:
            entity:
                class: App\Entity\Admin
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        admin:
            provider: db
            pattern: ^/admin/
            anonymous: ~
            switch_user: true
            form_login:
                login_path: admin_login
                check_path: admin_login_check
                default_target_path: easyadmin
            logout:
                path: admin_logout
                target: home
    access_control:
        - { path: ^/admin/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
    role_hierarchy:
        ROLE_ADMIN: ~
