version: '3'

services:
    base-php:
        build:
            context: ./services/php-base
            args:
                CHUBBYCOON_UID: ${CHUBBYCOON_UID}
        image: chubbycoon_basephp

    frontend:
        build: ./services/frontend
        depends_on:
            - base-php
        volumes:
            - ../../:/var/www:cached
        links:
            - database
        ports:
            - "80:80"

    database:
        image: mysql:5.7
        environment:
            MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
            MYSQL_DATABASE: 'chubbycoon'
            MYSQL_USER: 'chubbycoon'
            MYSQL_PASSWORD: 'chubbycoon'
        ports:
            - 3306:3306

    builder:
        build: ./services/builder
        env_file: ../../.env
        depends_on:
            - base-php
        volumes:
            - ../../:/home/chubbycoon/app:cached
        links:
            - database
