easy_admin:
    design:
        menu:
            - label: 'Administration'
            - { entity: 'Admin', icon: 'users', label: 'Administrateurs' }
            - { entity: 'Article', icon: 'newspaper-o', label: 'Articles' }
            - { entity: 'Category', icon: 'tags', label: 'Catégories' }
            - { route: 'admin_media_explorer', icon: 'picture-o', label: 'Media Explorer' }
