easy_admin:
    design:
        menu:
            - label: 'Manager'
            - { entity: 'Admin', icon: 'users', label: 'Administrateurs' }
            - { entity: 'Article', icon: 'newspaper-o', label: 'Articles' }
            - { entity: 'Category', icon: 'th-list', label: 'Catégories' }
            - label: 'Env: %env(APP_ENV)%'
