easy_admin:
    entities:
        Article:
            class: App\Entity\Article
            list:
                title: 'Tous les articles'
                actions:
                    - { name: 'show', label: 'Voir', 'icon': 'eye' }
                fields:
                    - { property: 'title', 'label': 'Titre' }
                    - { property: 'createdAt', 'label': 'Date de création' }
                    - { property: 'status', 'label': 'Statut', template: 'easy_admin/Article/list/status.html.twig' }
                    - { property: 'category', 'label': 'Catégorie' }
            new:
                title:  'Écrire un article'
            edit:
                title:  'Éditer un article'
            form:
                fields:
                    - { type: 'group', css_class: 'col-sm-6', icon: 'pencil', label: 'Principal' }
                    - { property: 'title', 'label': 'Titre' }
                    - { property: 'content', 'label': 'Contenu', type: 'FOS\CKEditorBundle\Form\Type\CKEditorType' }
                    - { type: 'group', css_class: 'col-sm-6', icon: 'cubes', label: 'Métadonnées' }
                    - { property: 'status', 'label': 'Status', type: 'App\Type\ArticleStatusType' }
                    - { property: 'category', 'label': 'Catégorie', type: 'easyadmin_autocomplete', type_options: { class: 'App\Entity\Category' } }
