easy_admin:
    entities:
        Category:
            class: App\Entity\Category
            list:
                fields:
                    - { property: 'name' }
            form:
                fields:
                    - { property: 'name', 'label': 'Nom' }