easy_admin:
    entities:
        Category:
            class: App\Entity\Category
            list:
                title: 'Toutes les catégories'
                actions: ['-show']
                fields:
                    - { property: 'name' }
            new:
                title:  'Créer une catégorie'
            edit:
                title:  'Modifier une catégorie'
            form:
                fields:
                    - { property: 'name', 'label': 'Nom' }
